name: golang-ci
on:
    pull_request:
        paths:
            - "**.go"
            - .github/workflows/golangci.yml

jobs:
    golangci-lint:
        name: golangcu-lint
        runs-on: ubuntu-latest
        steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v3
        - name: golangci-lint
          uses: reviewdog/action-golangci-lint@v2
          with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            golangci_lint_flags: "--config=./.golangci.yml ./..."
            fail_level: error
            reporter: "github-pr-review"