name: python-ci
on:
  pull_request:
    paths:
      - "**/*.py"
      - .github/workflows/pythonci.yml

jobs:
  pythonci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 履歴全体を取得
      - name: Determine branch from PR
        run: echo "Pull Request branch: ${{ github.head_ref }}"
      - name: Checkout PR branch
        run: |
          git fetch origin ${{ github.head_ref }}:$GITHUB_HEAD_REF
          git checkout $GITHUB_HEAD_REF
          git pull origin $GITHUB_HEAD_REF
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
      - name: Install black
        run: |
          pip install black
      - name: Run black
        run: |
          black --check . || (echo "Running black to format code..." && black .)
      - name: Commit and push changes
        if: success() && always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Apply black formatting [skip ci]" || echo "No changes to commit"
          git push
