name: Go Test Workflow

on:
  push:
    branches:
      - main  # mainブランチへのpush時に実行
  pull_request:
    branches:
      - main  # mainブランチへのPR作成・更新時に実行

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Devcontainer CLI
        run: npm install -g @devcontainers/cli
      - run: |
          echo $GITHUB_WORKSPACE
      - name: Build and test in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/example/example-devcontainer
          cacheFrom: ghcr.io/example/example-devcontainer
          push: always
          runCmd: go mod tidy && go test ./... -v -coverprofile=coverage.out

      # - name: Build and test in devcontainer
      #   run: |
      #     devcontainer build --workspace-folder $GITHUB_WORKSPACE --tag my-custom-devcontainer:latest
      #     pwd
      #     ls -la
      #     docker run -d --name my-devcontainer my-custom-devcontainer:latest
      #     devcontainer exec --workspace-folder $GITHUB_WORKSPACE "go mod tidy && go test ./... -v -coverprofile=coverage.out"
      - name: report coverage
        uses: k1LoW/octocov-action@v0